service: monitoring-tool

custom:
  email: jonathan.yu93@gmail.com
  frequency: 30 minutes

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - Ref : MonitoringNotificationTopic

package:
  artifact: target/monitoring-tool-dev.jar

functions:
  monitoring:
    handler: com.serverless.MonitoringHandler
    events:
      - schedule:
          rate: rate(${self:custom.frequency})
          input:
            monitors: ${file(monitors.json)}

resources:
  Resources:
    MonitoringNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Monitoring Notification Topic
        Subscription:
          -
            Endpoint: ${self:custom.email}
            Protocol: email